name: Sync appsettings.json to all repos

on:
  push:
    branches: [ "main" ]
    paths:
      - "appsettings.json"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sample_appsettings
        uses: actions/checkout@v4

      - name: Push to app-repo-1
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.APPSETTINGS_SAMPLE_PAT }}
        with:
          source_file: "appsettings.json"
          destination_repo: "vivekg2287749/app-repo-1"
          destination_branch: "main"
          user_email: "actions@github.com"
          user_name: "github-actions"
          commit_message: "sync: appsettings.json from sample_appsettings"

      - name: Push to app-repo-2
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.APPSETTINGS_SAMPLE_PAT }}
